-- ============================================================
-- BENZ AUTO DZ — SQL MASTER CONFIG (OSIRIS V10)
-- Copiez et collez TOUT dans Supabase > SQL Editor > Run
-- ============================================================

-- 1. NETTOYAGE COMPLET (Clean Slate)
DROP TABLE IF EXISTS site_settings CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS promo_codes CASCADE;

-- 2. STRUCTURE DES TABLES
-- Table des véhicules (Avec TOUS les champs du dashboard)
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  brand TEXT,
  model TEXT,
  year TEXT,
  price TEXT NOT NULL DEFAULT 'Sur demande',
  mileage TEXT,
  location TEXT DEFAULT 'Alger',
  engine TEXT,
  power TEXT,
  transmission TEXT DEFAULT 'Automatique',
  fuel TEXT DEFAULT 'Essence',
  category TEXT DEFAULT 'Luxe',
  image_url TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  description TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  is_visible BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'Disponible',
  views_count BIGINT DEFAULT 0
);

-- Table des demandes (Orders/Leads)
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  items_list TEXT,
  status TEXT DEFAULT 'Nouveau'
);

-- Table des paramètres (Configuration du site)
CREATE TABLE site_settings (
  id INT PRIMARY KEY DEFAULT 1,
  site_name TEXT DEFAULT 'Benz Auto DZ',
  contact_email TEXT DEFAULT 'contact@benzauto.dz',
  contact_phone TEXT DEFAULT '+213 555 00 00 00',
  address TEXT DEFAULT 'Alger, Algérie',
  social_links JSONB DEFAULT '{}'::jsonb,
  maintenance_mode BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table des administrateurs
CREATE TABLE admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  passcode TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table des vidéos (Même si cachée, la table doit exister)
CREATE TABLE videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  thumbnail TEXT NOT NULL,
  platform TEXT DEFAULT 'youtube',
  video_url TEXT NOT NULL
);

-- 3. INITIALISATION
INSERT INTO site_settings (id, site_name) VALUES (1, 'Benz Auto DZ') ON CONFLICT DO NOTHING;
INSERT INTO admins (name, passcode) VALUES ('Directeur Benz Auto', 'BENZ2026') ON CONFLICT DO NOTHING;

-- 4. SÉCURITÉ (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read" ON products FOR SELECT USING (true);
CREATE POLICY "Admin All" ON products FOR ALL USING (true);
CREATE POLICY "Public Read Settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Admin All Settings" ON site_settings FOR ALL USING (true);
CREATE POLICY "Public Insert Orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin All Orders" ON orders FOR ALL USING (true);
CREATE POLICY "Public Read Admins" ON admins FOR SELECT USING (true);
CREATE POLICY "Public Read Videos" ON videos FOR SELECT USING (true);
CREATE POLICY "Admin All Videos" ON videos FOR ALL USING (true);

-- 5. STORAGE
INSERT INTO storage.buckets (id, name, public) VALUES ('vehicles', 'vehicles', true) ON CONFLICT (id) DO NOTHING;

-- 6. SYNC
NOTIFY pgrst, 'reload schema';
