-- ============================================================
-- BENZ AUTO DZ — SQL CORE UPGRADE (OSIRIS V8)
-- Copiez et collez TOUT dans Supabase > SQL Editor > Run
-- ============================================================

-- ============================================================
-- PARTIE 1 : TABLES & STRUCTURE
-- ============================================================

-- Table des véhicules (Ressources)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  brand TEXT,
  category TEXT NOT NULL DEFAULT 'SUV',
  price TEXT NOT NULL,
  image_url TEXT,
  description TEXT,
  year TEXT,
  mileage TEXT,
  location TEXT DEFAULT 'Alger',
  engine TEXT,
  power TEXT,
  transmission TEXT DEFAULT 'Automatique',
  fuel TEXT DEFAULT 'Essence',
  images JSONB DEFAULT '[]'::jsonb,
  is_featured BOOLEAN DEFAULT FALSE,
  is_visible BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'Disponible',
  views_count BIGINT DEFAULT 0
);

-- Table des médias (Archives Visuelles)
CREATE TABLE IF NOT EXISTS videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  thumbnail TEXT NOT NULL,
  platform TEXT DEFAULT 'youtube',
  views TEXT,
  duration TEXT,
  video_url TEXT NOT NULL
);

-- Table des leads / commandes
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  items_list TEXT,
  status TEXT DEFAULT 'En attente'
);

-- Table des administrateurs (Kernel Access)
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  passcode TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertion de l'accès par défaut
INSERT INTO admins (name, passcode)
VALUES ('Benz Auto Admin', 'ZONE2026')
ON CONFLICT (passcode) DO NOTHING;

-- Table des paramètres (Kernel Configuration)
CREATE TABLE IF NOT EXISTS site_settings (
  id INT PRIMARY KEY DEFAULT 1,
  site_name TEXT DEFAULT 'Benz Auto DZ',
  contact_email TEXT DEFAULT '',
  contact_phone TEXT DEFAULT '',
  address TEXT DEFAULT '',
  social_links JSONB DEFAULT '{}'::jsonb,
  maintenance_mode BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Initialisation des paramètres
INSERT INTO site_settings (id, site_name)
VALUES (1, 'Benz Auto DZ')
ON CONFLICT (id) DO NOTHING;

-- Table des codes promos (Marketing Vectors)
CREATE TABLE IF NOT EXISTS promo_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_amount TEXT NOT NULL,
  discount_type TEXT DEFAULT 'percentage',
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table des logs système
CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  target TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- PARTIE 2 : SÉCURITÉ RLS (Row Level Security)
-- ============================================================

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;

-- Suppression des anciennes politiques
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Public Read" ON products;
    DROP POLICY IF EXISTS "Admin All Products" ON products;
    DROP POLICY IF EXISTS "Public Read Videos" ON videos;
    DROP POLICY IF EXISTS "Admin All Videos" ON videos;
    DROP POLICY IF EXISTS "Anyone Insert Orders" ON orders;
    DROP POLICY IF EXISTS "Admin All Orders" ON orders;
    DROP POLICY IF EXISTS "Public Read Admins" ON admins;
    DROP POLICY IF EXISTS "Public Read Settings" ON site_settings;
    DROP POLICY IF EXISTS "Admin All Settings" ON site_settings;
    DROP POLICY IF EXISTS "Public Read Promos" ON promo_codes;
    DROP POLICY IF EXISTS "Admin All Promos" ON promo_codes;
    DROP POLICY IF EXISTS "Admin All Logs" ON admin_logs;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Création des nouvelles politiques OSIRIS
CREATE POLICY "Public Read" ON products FOR SELECT USING (true);
CREATE POLICY "Admin All Products" ON products FOR ALL USING (true);

CREATE POLICY "Public Read Videos" ON videos FOR SELECT USING (true);
CREATE POLICY "Admin All Videos" ON videos FOR ALL USING (true);

CREATE POLICY "Anyone Insert Orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin All Orders" ON orders FOR ALL USING (true);

CREATE POLICY "Public Read Admins" ON admins FOR SELECT USING (true);

CREATE POLICY "Public Read Settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Admin All Settings" ON site_settings FOR ALL USING (true);

CREATE POLICY "Public Read Promos" ON promo_codes FOR SELECT USING (true);
CREATE POLICY "Admin All Promos" ON promo_codes FOR ALL USING (true);

CREATE POLICY "Admin All Logs" ON admin_logs FOR ALL USING (true);


-- ============================================================
-- PARTIE 3 : STORAGE BUCKET "vehicles"
-- ============================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('vehicles', 'vehicles', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Public Read Vehicles Storage" ON storage.objects;
    DROP POLICY IF EXISTS "Public Upload Vehicles Storage" ON storage.objects;
    DROP POLICY IF EXISTS "Public Update Vehicles Storage" ON storage.objects;
    DROP POLICY IF EXISTS "Public Delete Vehicles Storage" ON storage.objects;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

CREATE POLICY "Public Read Vehicles Storage" ON storage.objects FOR SELECT USING (bucket_id = 'vehicles');
CREATE POLICY "Public Upload Vehicles Storage" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'vehicles');
CREATE POLICY "Public Update Vehicles Storage" ON storage.objects FOR UPDATE USING (bucket_id = 'vehicles');
CREATE POLICY "Public Delete Vehicles Storage" ON storage.objects FOR DELETE USING (bucket_id = 'vehicles');

-- Final Schema Cache Refresh
NOTIFY pgrst, 'reload schema';
