-- ============================================================
-- BENZ AUTO DZ — SQL CORE UPGRADE (OSIRIS V9)
-- Copiez et collez TOUT dans Supabase > SQL Editor > Run
-- ============================================================

-- 1. NETTOYAGE RADICAL (Supprime les anciennes versions qui buggent)
DROP TABLE IF EXISTS site_settings CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS promo_codes CASCADE;
DROP TABLE IF EXISTS admin_logs CASCADE;

-- 2. STRUCTURE DES TABLES
-- Table des véhicules
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  brand TEXT,
  model TEXT,
  year TEXT,
  price TEXT NOT NULL DEFAULT 'Sur demande',
  mileage TEXT,
  engine TEXT,
  power TEXT,
  transmission TEXT DEFAULT 'Automatique',
  fuel TEXT DEFAULT 'Essence',
  category TEXT DEFAULT 'Luxe',
  image_url TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  description TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  is_visible BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'Disponible',
  views_count BIGINT DEFAULT 0
);

-- Table des demandes (Orders/Leads)
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  items_list TEXT,
  status TEXT DEFAULT 'Nouveau'
);

-- Table des paramètres (C'est ici que le bouton Enregistrer se répare)
CREATE TABLE site_settings (
  id INT PRIMARY KEY DEFAULT 1,
  site_name TEXT DEFAULT 'Benz Auto DZ',
  contact_email TEXT DEFAULT 'contact@benzauto.dz',
  contact_phone TEXT DEFAULT '+213 555 00 00 00',
  address TEXT DEFAULT 'Alger, Algérie',
  social_links JSONB DEFAULT '{}'::jsonb,
  maintenance_mode BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table des administrateurs
CREATE TABLE admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  passcode TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table des codes promos
CREATE TABLE promo_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_amount TEXT NOT NULL,
  discount_type TEXT DEFAULT 'percentage',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. INITIALISATION DES DONNÉES
INSERT INTO site_settings (id, site_name) VALUES (1, 'Benz Auto DZ');
INSERT INTO admins (name, passcode) VALUES ('Directeur Benz Auto', 'BENZ2026');

-- 4. SÉCURITÉ RLS (Row Level Security)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE promo_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);
CREATE POLICY "Admin All Products" ON products FOR ALL USING (true);
CREATE POLICY "Public Read Settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Admin All Settings" ON site_settings FOR ALL USING (true);
CREATE POLICY "Public Insert Orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin All Orders" ON orders FOR ALL USING (true);
CREATE POLICY "Public Read Promos" ON promo_codes FOR SELECT USING (true);
CREATE POLICY "Admin All Promos" ON promo_codes FOR ALL USING (true);
CREATE POLICY "Public Read Admins" ON admins FOR SELECT USING (true);

-- 5. STORAGE BUCKETS (Pour tes images)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('vehicles', 'vehicles', true) 
ON CONFLICT (id) DO NOTHING;

-- 6. FINALISATION
NOTIFY pgrst, 'reload schema';
