-- ==========================================
-- 1. TABLE DES PRODUITS (Véhicules)
-- ==========================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  brand TEXT,
  category TEXT NOT NULL DEFAULT 'SUV',
  price TEXT NOT NULL,
  image_url TEXT,
  description TEXT,
  year TEXT,
  mileage TEXT,
  location TEXT DEFAULT 'Alger',
  engine TEXT,
  power TEXT,
  transmission TEXT DEFAULT 'Automatique',
  fuel TEXT DEFAULT 'Essence',
  images JSONB DEFAULT '[]'::jsonb,
  is_featured BOOLEAN DEFAULT FALSE,
  is_visible BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'Disponible',
  views_count BIGINT DEFAULT 0
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON products FOR SELECT USING (true);
CREATE POLICY "Allow admin all" ON products FOR ALL USING (true);

-- ==========================================
-- 2. TABLE DES VIDÉOS (Vlogs & Tests)
-- ==========================================
CREATE TABLE IF NOT EXISTS videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  thumbnail TEXT NOT NULL,
  platform TEXT DEFAULT 'youtube',
  views TEXT,
  duration TEXT,
  video_url TEXT NOT NULL
);

ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read videos" ON videos FOR SELECT USING (true);
CREATE POLICY "Allow admin all videos" ON videos FOR ALL USING (true);

-- ==========================================
-- 3. TABLE DES DEMANDES (Inquiries)
-- ==========================================
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  items_list TEXT, -- Nom du véhicule concerné
  status TEXT DEFAULT 'En attente'
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anyone to insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin all orders" ON orders FOR ALL USING (true);

-- ==========================================
-- 4. TABLE ADMINS
-- ==========================================
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  passcode TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read admins" ON admins FOR SELECT USING (true);

INSERT INTO admins (name, passcode) 
VALUES ('Benz Auto Admin', 'ZONE2026')
ON CONFLICT (passcode) DO NOTHING;
